# IP/IP Range declear 
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.190-192.168.1.200

---
# Ip advertisement as ARP
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertise
  namespace: metallb-system
spec:
  ipAddressPools:
  - internal-pool